name: Unpublish NPM Versions by prefix

description: Unpublish NPM versions with a specific prefix, using the unpublish action for each matching version.

inputs:
  version_prefix:
    description: 'Prefix for the version to unpublish'
    required: true
  force:
    description: 'Force unpublish (default: false)'
    required: false
    default: 'false'
  confirm:
    description: 'Confirmation to proceed with unpublishing'
    required: false
  npm_token:
    description: "NPM token for authentication"
    required: true
outputs:
  UNPUBLISHED_VERSIONS_BY_PREFIX:
    description: 'The unpublished versions by prefix'
    value: ${{ steps.unpublish_versions_returned_by_prefix.outputs.UNPUBLISHED_VERSIONS_BY_PREFIX }}


runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org/'

    - name: Get Versions with Prefix
      id: get_versions
      shell: bash
      run: |
        # Get the versions with the specified prefix
        echo "⏳ Finding execution-engine versions with prefix ${{ inputs.version_prefix }}..."
        OLD_VERSIONS=$(npm dist-tag ls execution-engine | grep "${{ inputs.version_prefix }}" | awk '{print $2}' || true)
        
        if [ -z "$OLD_VERSIONS" ]; then
          echo "⚠️ No versions found with prefix ${{ inputs.version_prefix }}. Skipping."
          echo "OLD_VERSIONS=" >> $GITHUB_ENV
        else
          echo "✅ Versions found with prefix ${{ inputs.version_prefix }}: $OLD_VERSIONS"
          COMMA_SEPARATED_VERSIONS=$(echo "$OLD_VERSIONS" | tr '\n' ',')
          echo "Comma-separated versions: $COMMA_SEPARATED_VERSIONS"
          echo "OLD_VERSIONS=$COMMA_SEPARATED_VERSIONS" >> $GITHUB_ENV
        fi


    - name: Unpublish Versions
      id: unpublish_versions
      if: ${{ env.OLD_VERSIONS != '' }}
      uses: ./.github/actions/unpublish
      with:
        versions: ${{ env.OLD_VERSIONS }}
        force: ${{ inputs.force }}
        confirm: ${{ inputs.confirm }}
        npm_token: ${{ inputs.npm_token }}

    - name: Return Unpublished Versions
      if: ${{ env.OLD_VERSIONS != '' }}
      id: unpublish_versions_returned_by_prefix
      shell: bash
      run: |
        # Capture the output of the unpublish action
        UNPUBLISHED_VERSIONS="${{ steps.unpublish_versions.outputs.UNPUBLISHED_VERSIONS }}"
        echo "Unpublished versions: $UNPUBLISHED_VERSIONS"
        
        # Set the unpublished versions to the output
        echo "UNPUBLISHED_VERSIONS_BY_PREFIX=$UNPUBLISHED_VERSIONS" >> $GITHUB_ENV
        echo "UNPUBLISHED_VERSIONS_BY_PREFIX=$UNPUBLISHED_VERSIONS" >> $GITHUB_OUTPUT
