name: Publish beta

on:
  push:
    branches:
      - beta
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Choose release type (patch, minor, or major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Update and publish beta version
        run: |
          npm version ${{ github.event.inputs.release-type }} --preid=beta -m "chore: release ${{ github.event.inputs.release-type }} beta version %s"
          npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
