name: Publish beta

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Choose release type (patch, minor, or major). ⚠️ Only run on the beta branch!'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify beta branch
        run: |
          if [ "${{ github.ref }}" != "refs/heads/beta" ]; then
            echo "::error::This workflow can only be run on the beta branch. Please select the beta branch before triggering."
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Update and publish beta version
        run: |
          RELEASE_TYPE="${{ github.event.inputs.release-type }}"
          npm version $RELEASE_TYPE --preid=beta -m "chore: release $RELEASE_TYPE beta version %s"
          npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}