name: Publish canary to NPM

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]

jobs:
  canary:
    name: Publish Canary
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Generate Canary Version
        run: |
          BASE_VERSION=$(node -p "require('./package.json').version")
          PR_NUMBER=${{ github.event.pull_request.number }}
          COMMIT_HASH=${GITHUB_SHA::7}
          CANARY_VERSION="${BASE_VERSION}-canary.${PR_NUMBER}.${COMMIT_HASH}"
          CANARY_PREFIX="${BASE_VERSION}-canary.${PR_NUMBER}"
          
          echo "CANARY_VERSION=${CANARY_VERSION}"
          echo "CANARY_PREFIX=${CANARY_PREFIX}"
          
          echo "CANARY_VERSION=${CANARY_VERSION}" >> $GITHUB_ENV
          echo "CANARY_PREFIX=${CANARY_PREFIX}" >> $GITHUB_ENV

      - name: Remove old Canary versions
        run: |
          echo "Unpublishing versions for prefix: ${CANARY_PREFIX}..."
          VERSIONS=$(npm dist-tag ls execution-engine | grep "${CANARY_PREFIX}" | awk '{print $2}')
          if [ -z "$VERSIONS" ]; then
            echo "No versions found for prefix ${CANARY_PREFIX}. Nothing to unpublish."
          else
            for v in $VERSIONS; do
              echo "Unpublishing version: $v"
              npm unpublish --force execution-engine@$v
            done
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Bump Version and Publish Canary
        run: |
          npm version $CANARY_VERSION --no-git-tag-version
          npm publish --tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Comment on PR with deployed Version
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ✅ **Created Version:** `${{ env.CANARY_VERSION }}`
            📦 **Published on NPM:** [View on NPM](https://www.npmjs.com/package/execution-engine/v/${{ env.CANARY_VERSION }})

            > ⚠️ **Note:** This version is temporary and will be **unpublished** on the next PR update or merge.
          reactions: 'rocket'

  cleanup:
    name: Remove Canary Version
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove all PR Canary versions
        run: |
          BASE_VERSION=$(node -p "require('./package.json').version")
          PR_NUMBER=${{ github.event.pull_request.number }}
          CANARY_PREFIX="${BASE_VERSION}-canary.${PR_NUMBER}"
          echo "Unpublishing versions for prefix: ${CANARY_PREFIX}..."

          VERSIONS=$(npm dist-tag ls execution-engine | grep "${CANARY_PREFIX}" | awk '{print $2}')
          if [ -z "$VERSIONS" ]; then
            echo "No versions found for prefix ${CANARY_PREFIX}. Nothing to unpublish."
          else
            for v in $VERSIONS; do
              echo "Unpublishing version: $v"
              npm unpublish --force execution-engine@$v
            done
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
