name: Unpublish NPM Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to unpublish'
        required: true

jobs:
  unpublish:
    runs-on: ubuntu-latest

    steps:
      - name: Display Inputs
        run: echo "Attempting to unpublish execution-engine@${{ github.event.inputs.version }}"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Unpublish Version from NPM
        run: |
          echo "Unpublishing execution-engine@${{ github.event.inputs.version }}..."
          npm unpublish --force execution-engine@${{ github.event.inputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
